let gameSeq=[];                                     //game color sequence 
let userSeq=[];                                     // user color sequence 

let started=false;                                  //initially game has not started
let level=0;                                        //starting level is 0

let h2=document.querySelector("h2");

let btns=["pink", "orange", "green", "purple"]      //to generate random color

//step-1 : Game starts by pressing any key on keyboard
document.addEventListener("keypress",function(){
    if(started==false){                             //To start game only once i.e only when game is off
        console.log("game has started");
        started=true;

        levelUp();
    }
});

//Step-2 : After the game starts Increase the level, the level updation should be done in the h2 innerText and any Color Flashes
function btnFlash(btn){
    btn.classList.add("flash");                     //from css flash class background-color changes to white
    setTimeout(function(){                          //to create flash effect
        btn.classList.remove("flash");              
    },250) // 1/4 th of 1sec
}

function levelUp(){
    userSeq=[];
    level++;
    h2.innerText=`Level ${level}`;

    let randIdx=Math.floor(Math.random()*3);        //generates random  index from 1 to 3 because we have 4 colors in btns array
    let randColor=btns[randIdx];                    //generated random index is passed to btns array and stored in randomColor
    let randBtn=document.querySelector(`.${randColor}`);          

    /* randColor is a string representing the CSS class of a button (e.g., "red", "green", etc.)
    document.querySelector(\.${randColor}`)is used to select the button element that has the corresponding class. 
    The backticks `` `` are used for template literals to insert the value of randColor into the CSS selector.
    For example, if randColor is "red", this line will select the element with the class red. */

    gameSeq.push(randColor);

    btnFlash(randBtn);  //random button generated by the browser get flashed
}


function checkAns(idx){
    if(userSeq[idx] === gameSeq[idx]){
        if(userSeq.length==gameSeq.length){
            setTimeout(levelUp,1000);
        } 
    } else{
            h2.innerHTML=`GAME OVER! Your Score was <b>${level}</b> <br> Press any key to start.`;
            document.querySelector("body").style.backgroundColor="red";
            setTimeout(function(){
                document.querySelector("body").style.backgroundColor="white";
            },1000);
            reset();
        }
}

function btnPress(){
    let btn=this;
    btnFlash(btn);     //the button which we click get flashed

    userColor=btn.getAttribute("id");
    userSeq.push(userColor);

    checkAns(userSeq.length-1);
}

let allBtns=document.querySelectorAll(".btn");
for(btn of allBtns){
    btn.addEventListener("click",btnPress);
}

function reset(){
    started=false;
    gameSeq=[];
    userSeq=[];
    level=0;
}